### ISSUE TITLE
建议mybigword-personal-excluded-words调用一个单独的纯文本文件（一行一词）

### ISSUE THREAD

**Issue by heisaari** [redguardtoo/mybigword#4]
很好的功能，谢谢
拟将认知熟悉词排除掉，但数千个在一段中写在el文件里实在太长了
带着缩进和引号也不易维护
建议将这个调用做成读取一个personal-excluded-words的一行一词的纯文本文件
谢谢

**Comment by redguardtoo** [comment]
I think "el" is more flexiable. create one "my-dict.el" at "~/"
```lisp
(setq mybigword-personal-excluded-words
         '("word1"
            "word2"
             ...
             "word3"))
```

In you "~/.emacs", you can `(load-file "~/my-dict.el")`

If you still prefer plain text dictionary, add below code into "~/.emacs".
```lisp
(setq mybigword-excluded-words
      (split-string (with-temp-buffer
                      (insert-file-contents  "~/plain-text-dict.txt")
                      (buffer-string)) "[\r\n]+"))
```

**Comment by heisaari** [comment]
哇，感谢这么快地解决和指导！祝好！
