### ISSUE TITLE
关于如何一次性查完当前buffer生词的问题

### ISSUE THREAD

**Issue by oxsardbest** [redguardtoo/mybigword#7]
您好陈哥， 
需求是希望在新buffer显示所有生词和查询结果。
我已经设定好mybigword-format-with-dictionary，但是这个要dictd或者联网查询，我在家用没问题，目前单位都是内网(win7)。平时我用my-dict-simple用的很好，希望能把这两个结合起来，将生词一次性查完就更方便了。我用的词库只有stardict格式，没有dictd格式。

**Comment by redguardtoo** [comment]
13574e2 can use 3rd party dictionary api (Chen Bin).  You can set `mybigword-word-definition-function`

**Comment by oxsardbest** [comment]
陈哥太棒了，这次更新把单词输入提示框抽到外面了，我因为语法不熟，所以写了老是不行，原来是要写`(when ,word  学习了。
